### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by TammamT** [henrist/aqmt#1]
Hi, 
When running the "example.py"
the following error occurs.

Leafpadroot@aqm:/opt/testbed# TEST_INTERACTIVE=1 ./example.py
Traceback (most recent call last):
  File "./example.py", line 10, in <module>
    from aqmt import Testbed, TestEnv, run_test, steps
  File "/opt/aqmt/aqmt/__init__.py", line 29, in <module>
    from .testbed import Testbed, require_on_aqm_node
  File "/opt/aqmt/aqmt/testbed.py", line 54
    self.ip_classification = ip_class

This can be simply solved by replacing the "TAB" in the indentation of line 54 in file **"/opt/aqmt/aqmt/testbed.py"** with "Spaces"

**Comment by henrist** [comment]
Thanks for reporting. I'll have a look at this later this evening or tomorrow and sort this out.

**Comment by henrist** [comment]
Fixed in https://github.com/henrist/aqmt/commit/fa3fd57b2ace2097071e16f7fe06dd8e4dea01cb
